language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t udagram-api-feed ./Project3/udagram-api-feed
  - docker tag udagram-api-feed danhtran210/udagram-api-feed:latest
  - docker build -t udagram-api-user ./Project3/udagram-api-user
  - docker tag udagram-api-user danhtran210/udagram-api-user:latest
  - docker build -t udagram-frontend ./Project3/udagram-frontend
  - docker tag udagram-frontend danhtran210/udagram-frontend:latest
  - docker build -t reverseproxy ./Project3/udagram-reverseproxy
  - docker tag reverseproxy danhtran210/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danhtran210/udagram-api-feed
  - docker push danhtran210/udagram-api-user
  - docker push danhtran210/udagram-frontend
  - docker push danhtran210/reverseproxy
